name: Android CI Buildozer Stable

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Rimosso: Install Buildozer (Local)

      - name: Build APK via Kivy Docker Image (Installa e Compila)
        run: |
          # Questo comando esegue una shell bash nel container, installa l'ultima versione di Buildozer,
          # e poi esegue il comando di compilazione. La versione aggiornata rispetta warn_on_root = 0.
          docker run \
          --name buildozer_runner \
          -v $(pwd):/home/user/hostpython/ \
          -e 'BUILDOZER_PREFIX=/home/user' \
          kivy/buildozer /bin/bash -c "pip install buildozer --upgrade && buildozer android release" # <--- MODIFICA FINALE
        
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android.keystore

      - name: Sign APK
        run: |
          APK_PATH=$(find ./bin -name "*-release.apk" -print -quit)
          
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore android.keystore \
          -storepass ${{ secrets.KEYSTORE_PASS }} \
          $APK_PATH ${{ secrets.KEY_ALIAS }} \
          -keypass ${{ secrets.KEY_PASS }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk-release
          path: ./bin/*.apk
