name: Android CI Buildozer Docker

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Step 1: Decodifica Keystore (deve essere disponibile prima di Buildozer)
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android.keystore

      - name: Compile APK via Buildozer (Docker)
        # Passiamo alla branch master, che spesso include i fix pi√π recenti
        uses: ArtemSBulgakov/buildozer-action@master 
        id: buildozer
        with:
          command: buildozer android release
          # Riprova container_user, se la master lo supporta
          container_user: root 

      # Step 3: Firma e Upload
      - name: Rename and Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk-release
          path: bin/*.apk
          
