name: Android CI Buildozer Stable

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build APK via Kivy Docker (Forzatura Input Shell)
        run: |
          # Esegue una shell che reindirizza 'y' (yes) a Buildozer, risolvendo l'EOFError.
          docker run \
          --name buildozer_runner \
          -v $(pwd):/home/user/hostpython/ \
          kivy/buildozer sh -c "yes | buildozer android release" # <--- IL COMANDO FINALE
        
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android.keystore

      - name: Sign APK
        run: |
          APK_PATH=$(find ./bin -name "*-release.apk" -print -quit)
          
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore android.keystore \
          -storepass ${{ secrets.KEYSTORE_PASS }} \
          $APK_PATH ${{ secrets.KEY_ALIAS }} \
          -keypass ${{ secrets.KEY_PASS }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk-release
          path: ./bin/*.apk
