name: Android CI Buildozer Stable

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build APK via CI Docker Image
        run: |
          # Usa un'immagine Docker CI stabile che risolve i problemi di interattivitÃ .
          docker run \
          --name buildozer_ci_runner \
          -v $(pwd):/home/user/hostpython/ \
          bochecha/kivy-buildozer-ci buildozer android release
        
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android.keystore

      - name: Sign APK
        run: |
          APK_PATH=$(find ./bin -name "*-release.apk" -print -quit)
          
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore android.keystore \
          -storepass ${{ secrets.KEYSTORE_PASS }} \
          $APK_PATH ${{ secrets.KEY_ALIAS }} \
          -keypass ${{ secrets.KEY_PASS }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk-release
          path: ./bin/*.apk
